### ISSUE TITLE
evalコマンドを粛清する

### ISSUE THREAD

**Issue by TinyKitten** [TinyKitten/sugoibot#3]
こいつのせいでalpineイメージが使えない

**Comment by makotia** [comment]
ブチ切れで草

**Comment by TinyKitten** [comment]
すごいマジマージ卍 #6

**Comment by makotia** [comment]
closeって書いたら自動でcloseされるやつ知らない？？

**Comment by TinyKitten** [comment]
ADHDって言葉知らない？

**Comment by makotia** [comment]
これ？
![Image](https://i.imgur.com/o4enpcU.jpg)

**Comment by TinyKitten** [comment]
![D-1BHQyUYAAiY1c](https://user-images.githubusercontent.com/32848922/66568269-128e7280-eba4-11e9-85f0-a26ed4024e7e.jpg)
